### ISSUE TITLE
question about triggered ropchain

### ISSUE THREAD

**Issue by d4em0n** [ispras/rop-benchmark#2]
rop compiler generate ropchain to call syscall execve /bin/sh or to call function `void sys(char *s)` in vul.c?

**Comment by SweetVishnya** [comment]
ROP compiler invokes syscall `execve("/bin/sh", 0, 0)`.

**Comment by d4em0n** [comment]
but some of those bins doesn't have syscall gadget, is that intended?

**Comment by SweetVishnya** [comment]
Binaries were just taken from different linux distributions `/usr/bin` and `/usr/lib`.

https://github.com/ispras/rop-benchmark#real-life-binaries-test-suite

**Comment by SweetVishnya** [comment]
We may support other payloads (like funcion call) later.
